### ISSUE TITLE
Stable Tag

### ISSUE THREAD

**Issue by ghost** [iutbay/yii2-mm#1]
Hey 

could you mark a stable Version? Id like to test your manager, but i dont want to lower the requirements.

**Comment by klevron** [comment]
Hi

Not stable yet, but you can use this in `composer.json` :

```js
"minimum-stability": "dev",
"prefer-stable": true,
```

Feel free to report bugs and contribute :)

**Comment by ghost** [comment]
Hey 
thanks for this hint, worked for me. 

Im a little sad that i have to use bootstrap again, but thats ok
